# Generated by Django 3.2.25 on 2024-05-29 08:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='レコードID')),
                ('category_nm', models.CharField(max_length=20, unique=True, verbose_name='カテゴリ名')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者ID')),
            ],
            options={
                'verbose_name': '3.カテゴリ',
                'verbose_name_plural': '3.カテゴリ',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='レコードID')),
                ('book_id', models.CharField(max_length=30, unique=True, verbose_name='書籍ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='タイトル')),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), size=50, verbose_name='著者')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
                ('publisher', models.CharField(blank=True, max_length=30, null=True, verbose_name='出版社')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='発行日')),
                ('image_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='イメージ画像')),
                ('order_num', models.IntegerField(verbose_name='並び順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('completed_fg', models.BooleanField(default=False, verbose_name='読了フラグ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='読了日時')),
                ('category', models.ManyToManyField(blank=True, to='my_book_management.Category', verbose_name='カテゴリ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者ID')),
            ],
            options={
                'verbose_name': '1.読書リスト',
                'verbose_name_plural': '1.読書リスト',
                'db_table': 'reading_list',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='レコードID')),
                ('text', models.TextField(verbose_name='感想')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='五つ星評価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('reading_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_book_management.readinglist', verbose_name='読書リストID')),
            ],
            options={
                'verbose_name': '2.レビュー',
                'verbose_name_plural': '2.レビュー',
                'db_table': 'review',
            },
        ),
    ]
